# Generated by Django 4.2.2 on 2023-07-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('waitingapproval', 'Waiting approval'), ('active', 'active'), ('deleted', 'deleted')], default='active', max_length=50),
        ),
    ]
