# Generated by Django 4.2.2 on 2023-07-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='merchant_id',
            new_name='payment_intent',
        ),
    ]
